#!/usr/bin/env bash

DIR=`dirname "$BASH_SOURCE"`

cd "$DIR"

if ! type ruby &>/dev/null
then
	echo "Ruby not installed"
	exit 1;
else
	if ! type bundle &>/dev/null
	then
		echo "Bundler not installed."
		echo "Please install bundler with the following command: gem install bundle"
		exit 1;
	fi
fi

if ! type npm &>/dev/null
then
	echo "NPM not installed."
	exit 1;
fi

echo "Executing bundler"
bundle install

echo "NPM Install"
npm install

gulp

