#!/usr/bin/env bash

cd `dirname "$BASH_SOURCE"`

if ! type ruby &>/dev/null
then
	echo "Ruby not installed"
	exit 1;
else
	if !type bundle &>/dev/null
	then
		echo "Bundler not installed."
		echo "Please install bundler with the following command: gem install bundle"
		exit 1;
	fi
fi

if ! type npm &>/dev/null
then
	if type brew &>/dev/null
	then
		brew install npm
	else
		echo "NPM not installed."
		exit 1;
	fi
fi

echo "Executing bundler"
bundle install

# check if we need to execute npm install, if so, do it.
echo "NPM Install"
npm install

# Start default environment
gulp
